name: Workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: make packages
      - name: Run linters
        run: make lint

  backup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Create bundle
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          mkdir -p bundles
          git bundle create "bundles/${TIMESTAMP}_${{ github.event.repository.name }}.bundle" --all
      - name: Upload via curl
        run: |
          set -euo pipefail
          echo "Bundled files:"
          ls -l bundles || true
          for f in bundles/*; do
            [ -f "$f" ] || { echo "No bundle files found"; exit 1; }
            base=$(basename "$f")
            safe="${base%.bundle}.bin"
            # Show diagnostics before upload
            echo "\nPreparing upload for: $f"
            md5sum "$f" || true
            stat -c '%n %s bytes' "$f" 2>/dev/null || wc -c "$f"
            cp "$f" "/tmp/$safe"
            echo "Uploading as (renamed for FTP): /tmp/$safe -> /backups/$safe"
            curl -v --quote "TYPE I" --ftp-method nocwd \
              -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
              --ssl-reqd --ftp-pasv --disable-epsv --ftp-create-dirs \
              -T "/tmp/$safe" "ftp://${{ secrets.FTP_HOSTNAME }}:21/backups/$safe"
          done
          echo "\nList /backups:"
          curl -u "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
            --ssl-reqd --ftp-pasv --disable-epsv --ftp-method nocwd \
            "ftp://${{ secrets.FTP_HOSTNAME }}:21/backups/" -l || true
